# -*- coding: utf-8 -*-
"""main.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1eAVWVuYE3yWcMN07WAWJBaKwcSTm2few
"""

# --- Install packages ---
!pip install torch torchvision torchaudio --index-url https://download.pytorch.org/whl/cu118
!pip install transformers datasets gradio Pillow

# --- Imports ---
from transformers import BlipProcessor, BlipForConditionalGeneration
from PIL import Image
import requests
import gradio as gr

# --- Load Pretrained Model ---
processor = BlipProcessor.from_pretrained("Salesforce/blip-image-captioning-base")
model = BlipForConditionalGeneration.from_pretrained("Salesforce/blip-image-captioning-base")

# --- Test with example image ---
url = "https://images.unsplash.com/photo-1503023345310-bd7c1de61c7d"
image = Image.open(requests.get(url, stream=True).raw)

inputs = processor(images=image, return_tensors="pt")
out = model.generate(**inputs)
caption = processor.decode(out[0], skip_special_tokens=True)
print("Caption:", caption)

# --- Gradio Interface ---
def generate_caption(image):
    inputs = processor(images=image, return_tensors="pt")
    out = model.generate(**inputs)
    caption = processor.decode(out[0], skip_special_tokens=True)
    return caption

iface = gr.Interface(
    fn=generate_caption,
    inputs=gr.Image(type="pil"),
    outputs="text",
    title="Image Captioning AI",
    description="Upload any image and get a descriptive caption."
)

iface.launch()  # Provides free public URL in Colab
